<div class="row">
    <div class="col-md-12">
        <form action="/twitter" class="form">
            <div class="form-group">
                <label for="profile">profile</label>
                <input type="text" id="profile" name="profile" class="form-control">
                <input type="submit" value="submit" class="btn btn-primary">
            </div>
        </form>
    </div>
    <div class="col-md-12 hidden" id="address">
        <dl>
            <dt>Location</dt>
            <dd id="location"></dd>
            <dt>Link</dt>
            <dd><a href="" id="link" target="_blank">Link to Google Maps</a></dd>
        </dl>
    </div>
</div>
<?= $this->inlineScript()->captureStart(); ?>
    $('.form').submit(function(e){
        e.preventDefault();
        $('#address').addClass('hidden');
        var username = $('#profile').val()

        $.ajax({
            type: 'GET',
            url: '/twitter/' + username,
            dataType: 'json'
        }).fail(function(){
            alert('Usuário não encontrado');
        }).done(function(data) {
            $('#address').removeClass('hidden');
            $('#location').html(data.placeName);
            $('#link').attr('href', data.link);
        })
    });
<?= $this->inlineScript()->captureEnd(); ?>
